name: Setup
inputs:
  USE_LOCKFILE:
    required: true
    type: boolean

# note it cannot contain the checkout, the must be checked out in the calling workflow or it will not be able to find the composite action
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: latest

    - uses: actions/setup-node@v4
      name: Setting up node.js (${{ matrix.node-version }})
      with:
        node-version: ${{ matrix.node-version }}

    - uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: Get Pnpm Cache Path
      id: pnpm-cache
      run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      name: pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - run: "echo Cache Key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"
    - run: "echo Cache Restore-Keys: ${{ runner.os }}-pnpm-store-"
    - run: "echo Pnpm Cache Hit: ${{ steps.pnpm-cache.outputs.cache-hit }}"

    - run: pnpm install --frozen-lockfile
      name: Installing Dependencies
      if: "inputs.USE_LOCKFILE == 'true'"
      shell: bash

    - run: pnpm install --no-lockfile
      name: Installing Dependencies
      if: "inputs.USE_LOCKFILE != 'true'"
      shell: bash

