name: Build
# not technically necessary because release also runs tests but this way the build badge is separate

env:
  USE_LOCKFILE: ${{ secrets.USE_LOCKFILE }}

on:
  #TOCONFIGURE
  # schedule:
  #   # every first of the month at 12:00 noon GMT-3
  #   # https://crontab.guru/#0_12_1_*_*
  #   - cron:  '0 15 1 * *'
  push:
    branches: [ master , build, experimental ]
  repository_dispatch:
    types: [ build ]

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/*", "latest"]

    steps:

    # region Setup
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      id: pnpm-install
      with:
        version: latest

    - uses: actions/setup-node@v4
      name: Setting Up Node.js (${{ matrix.node-version }})
      with:
        node-version: ${{ matrix.node-version }}
        cache: ${{ env.USE_LOCKFILE == 'true' && 'pnpm' || '' }}

    - run: pnpm install --frozen-lockfile
      if: "env.USE_LOCKFILE == 'true'"

    - run: pnpm install --no-lockfile
      if: "env.USE_LOCKFILE != 'true'"
    # regionend

    # region Steps

    - run: pnpm build

    - run: pnpm lint

    - run: pnpm test
    # regionend
