name: Docs 

env:
  ENABLE_DOCS: ${{ secrets.ENABLE_DOCS }}

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ docs ]

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]') && ! contains(toJSON(github.event.commits.*.message), '(no-release)')"
    secrets: inherit

  docs:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["lts/*"]
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/composite-setup
      with:
        USE_LOCKFILE: ${{ secrets.USE_LOCKFILE }}

    - run: pnpm doc

    - name: Documentation
      if: "env.ENABLE_DOCS == 'true'"
      uses: crazy-max/ghaction-github-pages@v4
      with:
        jekyll: false
        target_branch: gh-pages
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: echo "env.ENABLE_DOCS is ${{ fromJSON(env.ENABLE_DOCS) }}, no documentation can be published" && exit 1
      if: "env.ENABLE_DOCS != 'true'"
